/**
 * NCRP Cyber Crime Report Generator
 * ===================================
 * Generates a forensic-quality PDF report that mirrors the National
 * Cyber Crime Reporting Portal (NCRP) format.  Includes victim/attacker
 * UPI details, ML risk scores, device telemetry, 7-layer analysis, and
 * safety recommendations — everything the police need in one document.
 */

import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

// ── Interfaces (subset of PaymentFlowV2 types) ────────────────────

interface LayerResult {
  name: string
  passed: boolean
  score: number
  status: 'safe' | 'warning' | 'danger'
}

interface SecurityAnalysis {
  transaction_id: string
  risk_level: string
  risk_level_label: string
  final_score: number
  is_blocked: boolean
  can_proceed: boolean
  primary_reason: string
  all_reasons: string[]
  safety_tips: string[]
  scam_type_detected: string | null
  scam_type_label: string | null
  layer_summary: LayerResult[]
}

interface SensorSnapshot {
  gyroscope: { x: number; y: number; z: number }
  accelerometer: { x: number; y: number; z: number }
  touch_pressure: number
  typing_speed: number
}

export interface NCRPReportData {
  // Victim
  victimName: string
  victimUPI: string
  victimPhone: string

  // Attacker / Recipient
  attackerUPI: string
  attackerName?: string
  attackerBank?: string

  // Transaction
  amount: number
  note?: string
  timestamp: Date

  // ML Analysis
  securityAnalysis: SecurityAnalysis
  layerResults: LayerResult[]

  // Device Telemetry
  sensorData: SensorSnapshot
  isOnCall: boolean

  // Optional scammer intel
  scammerReportCount?: number
  scammerWarning?: string
}

// ── Helpers ────────────────────────────────────────────────────────

const riskBadge = (level: string) => {
  const map: Record<string, string> = {
    safe: 'LOW RISK',
    caution: 'MODERATE RISK',
    risky: 'HIGH RISK',
    dangerous: 'CRITICAL RISK',
    blocked: 'BLOCKED — CONFIRMED THREAT',
  }
  return map[level] || level.toUpperCase()
}

const stressLevel = (sensor: SensorSnapshot): string => {
  const gyroMag = Math.sqrt(
    sensor.gyroscope.x ** 2 + sensor.gyroscope.y ** 2 + sensor.gyroscope.z ** 2,
  )
  if (gyroMag > 5) return 'HIGH STRESS / COERCION DETECTED'
  if (gyroMag > 2) return 'ELEVATED — POSSIBLE DURESS'
  return 'NORMAL'
}

const formatDate = (d: Date) =>
  d.toLocaleString('en-IN', {
    dateStyle: 'full',
    timeStyle: 'medium',
    timeZone: 'Asia/Kolkata',
  })

// ── Main Generator ─────────────────────────────────────────────────

export function generateNCRPReport(data: NCRPReportData): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  let y = 15

  // ─── Header ────────────────────────────────────────────
  doc.setFillColor(17, 24, 39) // slate-900
  doc.rect(0, 0, pageWidth, 38, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text('CYBER CRIME INCIDENT REPORT', pageWidth / 2, y, { align: 'center' })
  y += 7
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('National Cyber Crime Reporting Portal (NCRP) Format', pageWidth / 2, y, { align: 'center' })
  y += 6
  doc.setFontSize(8)
  doc.text(`Generated by UPI SafeGuard AI  •  ${formatDate(new Date())}`, pageWidth / 2, y, { align: 'center' })
  y += 5
  doc.setFontSize(7)
  doc.text(`Report ID: NCRP-${data.securityAnalysis.transaction_id.slice(0, 8).toUpperCase()}`, pageWidth / 2, y, { align: 'center' })

  y = 44

  // ─── Risk Level Banner ─────────────────────────────────
  const riskColors: Record<string, [number, number, number]> = {
    safe: [22, 163, 74],
    caution: [234, 179, 8],
    risky: [249, 115, 22],
    dangerous: [220, 38, 38],
    blocked: [127, 29, 29],
  }
  const bgColor = riskColors[data.securityAnalysis.risk_level] || [107, 114, 128]
  doc.setFillColor(...bgColor)
  doc.roundedRect(14, y, pageWidth - 28, 14, 3, 3, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.text(
    `THREAT ASSESSMENT: ${riskBadge(data.securityAnalysis.risk_level)}  —  Confidence: ${data.securityAnalysis.final_score}%`,
    pageWidth / 2,
    y + 9,
    { align: 'center' },
  )
  y += 20

  doc.setTextColor(0, 0, 0)

  // ─── Section 1: Transaction Details ────────────────────
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('1. TRANSACTION DETAILS', 14, y)
  y += 2

  autoTable(doc, {
    startY: y,
    margin: { left: 14, right: 14 },
    theme: 'grid',
    headStyles: { fillColor: [31, 41, 55], textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 55 } },
    head: [['Field', 'Value']],
    body: [
      ['Transaction ID', data.securityAnalysis.transaction_id],
      ['Date & Time', formatDate(data.timestamp)],
      ['Amount (₹)', `₹ ${data.amount.toLocaleString('en-IN')}`],
      ['Payment Note', data.note || '—'],
      ['Risk Level', riskBadge(data.securityAnalysis.risk_level)],
      ['Primary Threat', data.securityAnalysis.primary_reason],
      ['Scam Type Detected', data.securityAnalysis.scam_type_label || 'None identified'],
    ],
  })

  y = (doc as any).lastAutoTable.finalY + 8

  // ─── Section 2: Victim & Attacker Details ──────────────
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('2. PARTIES INVOLVED', 14, y)
  y += 2

  autoTable(doc, {
    startY: y,
    margin: { left: 14, right: 14 },
    theme: 'grid',
    headStyles: { fillColor: [31, 41, 55], textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 55 } },
    head: [['Party', 'Details']],
    body: [
      ['Victim Name', data.victimName],
      ['Victim UPI (VPA)', data.victimUPI || '—'],
      ['Victim Phone', data.victimPhone],
      ['Attacker UPI (VPA)', data.attackerUPI],
      ['Attacker Name', data.attackerName || 'UNVERIFIED'],
      ['Attacker Bank', data.attackerBank || 'Unknown'],
      ['Prior Scam Reports', data.scammerReportCount != null ? String(data.scammerReportCount) : '—'],
      ['Intel Warning', data.scammerWarning || '—'],
    ],
  })

  y = (doc as any).lastAutoTable.finalY + 8

  // ─── Section 3: 7-Layer Security Analysis ──────────────
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('3. 7-LAYER SECURITY SHIELD ANALYSIS', 14, y)
  y += 2

  const layerNames = ['Environment', 'Sanitization', 'Hard Rules', 'Verification', 'Risk Check', 'Community Intel', 'Final Decision']
  const layerRows = data.layerResults.map((lr, i) => [
    `Layer ${i + 1}: ${layerNames[i] || lr.name}`,
    lr.passed ? 'PASSED' : 'FAILED',
    `${lr.score}%`,
    lr.status.toUpperCase(),
  ])

  autoTable(doc, {
    startY: y,
    margin: { left: 14, right: 14 },
    theme: 'grid',
    headStyles: { fillColor: [31, 41, 55], textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 55 } },
    head: [['Security Layer', 'Result', 'Score', 'Status']],
    body: layerRows,
    didParseCell: (hookData) => {
      if (hookData.section === 'body' && hookData.column.index === 1) {
        const val = hookData.cell.raw as string
        if (val === 'FAILED') {
          hookData.cell.styles.textColor = [220, 38, 38]
          hookData.cell.styles.fontStyle = 'bold'
        } else {
          hookData.cell.styles.textColor = [22, 163, 74]
        }
      }
    },
  })

  y = (doc as any).lastAutoTable.finalY + 8

  // ─── Section 4: Device Telemetry & Coercion ────────────
  // Check if we need a new page
  if (y > 230) {
    doc.addPage()
    y = 15
  }

  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('4. DEVICE TELEMETRY & BEHAVIORAL ANALYSIS', 14, y)
  y += 2

  const stress = stressLevel(data.sensorData)
  const gyroMag = Math.sqrt(
    data.sensorData.gyroscope.x ** 2 +
    data.sensorData.gyroscope.y ** 2 +
    data.sensorData.gyroscope.z ** 2,
  ).toFixed(2)

  autoTable(doc, {
    startY: y,
    margin: { left: 14, right: 14 },
    theme: 'grid',
    headStyles: { fillColor: [31, 41, 55], textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 55 } },
    head: [['Metric', 'Reading']],
    body: [
      ['Gyroscope (rad/s)', `X: ${data.sensorData.gyroscope.x.toFixed(2)}  Y: ${data.sensorData.gyroscope.y.toFixed(2)}  Z: ${data.sensorData.gyroscope.z.toFixed(2)}`],
      ['Gyroscope Magnitude', `${gyroMag} rad/s`],
      ['Accelerometer (m/s²)', `X: ${data.sensorData.accelerometer.x.toFixed(2)}  Y: ${data.sensorData.accelerometer.y.toFixed(2)}  Z: ${data.sensorData.accelerometer.z.toFixed(2)}`],
      ['Touch Pressure', `${(data.sensorData.touch_pressure * 100).toFixed(0)}%`],
      ['Typing Speed', `${data.sensorData.typing_speed} WPM`],
      ['Stress / Coercion State', stress],
      ['Phone Call Active', data.isOnCall ? 'YES — SUSPICIOUS (possible vishing)' : 'No'],
    ],
    didParseCell: (hookData) => {
      if (hookData.section === 'body') {
        const field = hookData.row.cells[0]?.raw as string
        const val = hookData.cell.raw as string
        if (field === 'Stress / Coercion State' && val.includes('HIGH')) {
          hookData.cell.styles.textColor = [220, 38, 38]
          hookData.cell.styles.fontStyle = 'bold'
        }
        if (field === 'Phone Call Active' && val.startsWith('YES')) {
          hookData.cell.styles.textColor = [220, 38, 38]
          hookData.cell.styles.fontStyle = 'bold'
        }
      }
    },
  })

  y = (doc as any).lastAutoTable.finalY + 8

  // ─── Section 5: Risk Factors & Reasons ─────────────────
  if (y > 230) {
    doc.addPage()
    y = 15
  }

  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('5. IDENTIFIED RISK FACTORS', 14, y)
  y += 2

  const reasonRows = data.securityAnalysis.all_reasons.map((r, i) => [`${i + 1}`, r])
  if (reasonRows.length === 0) {
    reasonRows.push(['—', 'No specific risk factors identified'])
  }

  autoTable(doc, {
    startY: y,
    margin: { left: 14, right: 14 },
    theme: 'grid',
    headStyles: { fillColor: [31, 41, 55], textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    columnStyles: { 0: { cellWidth: 12, halign: 'center' } },
    head: [['#', 'Risk Factor / Threat Description']],
    body: reasonRows,
  })

  y = (doc as any).lastAutoTable.finalY + 8

  // ─── Section 6: Safety Advisory ────────────────────────
  if (y > 240) {
    doc.addPage()
    y = 15
  }

  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('6. SAFETY RECOMMENDATIONS', 14, y)
  y += 2

  const tipRows = data.securityAnalysis.safety_tips.map((tip, i) => [`${i + 1}`, tip])
  if (tipRows.length === 0) {
    tipRows.push(['—', 'No additional safety tips'])
  }

  autoTable(doc, {
    startY: y,
    margin: { left: 14, right: 14 },
    theme: 'grid',
    headStyles: { fillColor: [22, 101, 52], textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    columnStyles: { 0: { cellWidth: 12, halign: 'center' } },
    head: [['#', 'Recommendation']],
    body: tipRows,
  })

  y = (doc as any).lastAutoTable.finalY + 10

  // ─── Footer ────────────────────────────────────────────
  if (y > 250) {
    doc.addPage()
    y = 15
  }

  doc.setFillColor(243, 244, 246)
  doc.roundedRect(14, y, pageWidth - 28, 30, 3, 3, 'F')
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(55, 65, 81)
  doc.text('HOW TO FILE THIS REPORT', 18, y + 6)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7.5)
  doc.text('1.  Visit https://cybercrime.gov.in  →  File a Complaint  →  Report Other Cyber Crime', 18, y + 12)
  doc.text('2.  Call the Cyber Crime Helpline: 1930 (available 24/7)', 18, y + 17)
  doc.text('3.  Attach this PDF as supporting evidence along with bank statements & screenshots', 18, y + 22)
  doc.text('4.  Keep the Transaction ID for tracking:  ' + data.securityAnalysis.transaction_id, 18, y + 27)

  y += 36

  doc.setFontSize(7)
  doc.setTextColor(156, 163, 175)
  doc.text(
    'This report was auto-generated by UPI SafeGuard AI and is intended as supporting documentation for cyber crime complaints.',
    pageWidth / 2,
    y,
    { align: 'center' },
  )
  doc.text(
    'It does not constitute legal advice. Verify all details before submission.',
    pageWidth / 2,
    y + 4,
    { align: 'center' },
  )

  // ─── Save ──────────────────────────────────────────────
  const filename = `NCRP_Report_${data.securityAnalysis.transaction_id.slice(0, 8)}_${new Date().toISOString().split('T')[0]}.pdf`
  doc.save(filename)
}
